In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
video_game = pd.read_csv('~/Downloads/VideoGame/vgsales.csv')
video_game

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [122]:
drop_columns = video_game.drop(columns=['Rank', 'Year', 'Publisher'])
drop_columns

,Name,Platform,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,Sports,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,Platform,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,Racing,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,Sports,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,Role-Playing,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...
16593,Woody Woodpecker in Crazy Castle 5,GBA,Platform,0.01,0.00,0.00,0.00,0.01
16594,Men in Black II: Alien Escape,GC,Shooter,0.01,0.00,0.00,0.00,0.01
16595,SCORE International Baja 1000: The Official Game,PS2,Racing,0.00,0.00,0.00,0.00,0.01
16596,Know How 2,DS,Puzzle,0.00,0.01,0.00,0.00,0.01
16597,Spirits & Spells,GBA,Platform,0.01,0.00,0.00,0.00,0.01

In [123]:
group_sum = drop_columns.groupby(['Genre']).sum()
group_sum

              NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Genre
Action          877.83    525.00    159.95       187.38       1751.18
Adventure       105.80     64.13     52.07        16.81        239.04
Fighting        223.59    101.32     87.35        36.68        448.91
Misc            410.24    215.98    107.76        75.32        809.96
Platform        447.05    201.63    130.77        51.59        831.37
Puzzle          123.78     50.78     57.31        12.55        244.95
Racing          359.42    238.39     56.69        77.27        732.04
Role-Playing    327.28    188.06    352.31        59.61        927.37
Shooter         582.60    313.27     38.28       102.69       1037.37
Simulation      183.31    113.38     63.70        31.52        392.20
Sports          683.35    376.85    135.37       134.97       1330.93
Strategy         68.70     45.34     49.46        11.36        175.12

In [124]:
mean_data = drop_columns.groupby(['Genre']).mean()
mean_data

              NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Genre
Action        0.264726  0.158323  0.048236     0.056508      0.528100
Adventure     0.082271  0.049868  0.040490     0.013072      0.185879
Fighting      0.263667  0.119481  0.103007     0.043255      0.529375
Misc          0.235906  0.124198  0.061967     0.043312      0.465762
Platform      0.504571  0.227573  0.147596     0.058228      0.938341
Puzzle        0.212680  0.087251  0.098471     0.021564      0.420876
Racing        0.287766  0.190865  0.045388     0.061865      0.586101
Role-Playing  0.219946  0.126384  0.236767     0.040060      0.623233
Shooter       0.444733  0.239137  0.029221     0.078389      0.791885
Simulation    0.211430  0.130773  0.073472     0.036355      0.452364
Sports        0.291283  0.160635  0.057702     0.057532      0.567319
Strategy      0.100881  0.066579  0.072628     0.016681      0.257151

In [125]:
column = video_game['Global_Sales'].max()
column

82.74

In [126]:
column_index = video_game['Global_Sales'].idxmax()
column_index

0

In [127]:
highest_sold_game = video_game.iloc[0,:]
highest_sold_game

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

In [130]:
group_platform = drop_columns.groupby(['Platform']).sum()
group_platform

          NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
2600         90.60      5.47      0.00         0.91         97.08
3DO           0.00      0.00      0.10         0.00          0.10
3DS          78.87     58.52     97.35        12.63        247.46
DC            5.43      1.69      8.56         0.27         15.97
DS          390.71    194.65    175.57        60.53        822.49
GB          114.32     47.82     85.12         8.20        255.45
GBA         187.54     75.25     47.33         7.73        318.50
GC          133.46     38.71     21.58         5.18        199.36
GEN          19.27      5.52      2.67         0.89         28.36
GG            0.00      0.00      0.04         0.00          0.04
N64         139.02     41.06     34.22         4.38        218.88
NES         125.94     21.15     98.65         5.31        251.07
NG            0.00      0.00      1.44         0.00          1.44
PC           93.28    139.68      0.17        24.86        258.82
PCFX          0.00      0.00      0.03         0.00          0.03
PS          336.51    213.60    139.82        40.91        730.66
PS2         583.84    339.29    139.20       193.44       1255.64
PS3         392.26    343.71     79.99       141.93        957.84
PS4          96.80    123.70     14.30        43.36        278.10
PSP         108.99     68.25     76.79        42.19        296.28
PSV          16.20     16.33     20.96         8.45         61.93
SAT           0.72      0.54     32.26         0.07         33.59
SCD           1.00      0.36      0.45         0.05          1.87
SNES         61.23     19.04    116.55         3.22        200.05
TG16          0.00      0.00      0.16         0.00          0.16
WS            0.00      0.00      1.42         0.00          1.42
Wii         507.71    268.38     69.35        80.61        926.71
WiiU         38.32     24.23     12.79         6.45         81.86
X360        601.05    280.58     12.43        85.54        979.96
XB          186.69     60.95      1.38         8.72        258.26
XOne         83.19     45.65      0.34        11.92        141.06

In [134]:
drop_group_platform = group_platform.drop(columns=['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']).idxmax()
drop_group_platform

Global_Sales    PS2
dtype: object